### ISSUE TITLE
linitl-devel dependency

### ISSUE THREAD

**Issue by djuskus** [kgraefe/neovim-cygwin#6]
What is this dependency? I cannot find it. Is this a typo?

**Comment by kgraefe** [comment]
it's a typo, should be `libintl-devel`

**Comment by kgraefe** [comment]
the list `build-requires.txt` is what is actually used by the build scripts ;-)

**Comment by djuskus** [comment]
thanks

**Comment by kgraefe** [comment]
I will reopen it as a reminder for me to update the README

**Comment by kgraefe** [comment]
Fixed in faf76a9
